// Action script...

// [onClipEvent of sprite 2048 in frame 1]
onClipEvent (load)
{
    textStringArray = ["HERE\'S A GOOD PLACE TO PRACTICE YOUR WALL CLIMBING. HOLD THE DIRECTION TOWARDS A WALL AND YOU\'LL CLING TO IT. IF YOU        HOLD UP AND TOWARDS THE WALL WHILE HITTING THE WALL, YOU   CAN CLIMB UP A SHORT DISTANCE.  OH, AND YOU CAN WALL JUMP."];
}
