window.CGMT_ARCADE_GAMES = [
	// Standard cabinets
	{ name: "Patapon", slug: "patapon", file: "patapon.swf", category: "standard" },
	{ name: "Fancy Pants", slug: "the_fancy_pants_adventures", file: "the_fancy_pants_adventures.swf", category: "standard" },
	{ name: "Go Go Happy Smile", slug: "gogohappysmile", file: "gogohappysmile.swf", category: "standard" },
	{ name: "Neverending Light", slug: "neverendinglight", file: "neverendinglight.swf", category: "standard" },
	{ name: "Super Mario 63", slug: "supermario63", file: "supermario63.swf", category: "standard" },
	{ name: "Shift", slug: "shift", file: "shift.swf", category: "standard" },
	{ name: "Portal", slug: "portal", file: "portal.swf", category: "standard" },
	{ name: "The Game", slug: "thegame", file: "thegame.swf", category: "standard" },
	{ name: "Dino Run", slug: "dinorun", file: "dinorun.swf", category: "standard" },
	{ name: "Morning Star", slug: "morningstar", file: "morningstar.swf", category: "standard" },
	{ name: "The Last Stand", slug: "thelaststand", file: "thelaststand.swf", category: "standard" },
	{ name: "Super Karoshi", slug: "superkaroshi", file: "superkaroshi.swf", category: "standard" },
	{ name: "n", slug: "ngame", file: "ngame.swf", category: "standard" },
	{ name: "Sprite Smash", slug: "spritesmash", file: "spritesmash.swf", category: "standard" },
	{ name: "Heavy Weapons", slug: "heavyweapons", file: "heavyweapons.swf", category: "standard" },
	{ name: "Metal Slug", slug: "metalslug", file: "metalslug.swf", category: "standard" },
	{ name: "flow", slug: "flow", file: "flow.swf", category: "standard" },
	{ name: "Hover Kart", slug: "hoverkart", file: "hoverkart.swf", category: "standard" },
	{ name: "Ballracer", slug: "ballracer", file: "ballracer.swf", category: "standard" },
	{ name: "Mirrors Edge 2D", slug: "mirrorsedge2d", file: "mirrorsedge2d.swf", category: "standard" },
	{ name: "Paws", slug: "paws", file: "paws.swf", category: "standard" },
	{ name: "Vox Populi", slug: "voxpopuli", file: "voxpopuli.swf", category: "standard" },
	{ name: "More Zombies", slug: "morezombies", file: "morezombies.swf", category: "standard" },
	{ name: "Epsilon", slug: "epsilon", file: "epsilon.swf", category: "standard" },
	{ name: "Ultimate Flash Sonic", slug: "ultimateflashsonic", file: "ultimateflashsonic.swf", category: "standard" },
	{ name: "VVVVVV", slug: "vvvvvv", file: "vvvvvv.swf", category: "standard" },
	{ name: "Meat Boy", slug: "meatboy", file: "meatboy.swf", category: "standard" },
	{ name: "Dad and Me", slug: "dadandme", file: "dadandme.swf", category: "standard" },
	{ name: "Canabalt", slug: "canabalt", file: "canabalt.swf", category: "standard" },
	{ name: "Alien Hominid", slug: "alienhominid", file: "alienhominid.swf", category: "standard" },

	// Retro cabinets
	{ name: "Galaga", slug: "galaga", file: "galaga.swf", category: "retro" },
	{ name: "Asteroids", slug: "asteroids", file: "asteroids.swf", category: "retro" },
	{ name: "Donkey Kong", slug: "donkeykong", file: "donkeykong.swf", category: "retro" },
	{ name: "Final Fight", slug: "finalfight", file: "finalfight.swf", category: "retro" },
	{ name: "Ghosts and Goblins", slug: "ghostsandgoblins", file: "ghostsandgoblins.swf", category: "retro" },
	{ name: "Puzzle Bobble", slug: "puzzlebobble", file: "puzzlebobble.swf", category: "retro" },
	{ name: "Raiden", slug: "raiden", file: "raiden.swf", category: "retro" },
	{ name: "Rick Dangerous", slug: "rickdangerous", file: "rickdangerous.swf", category: "retro" },
	{ name: "KungFu", slug: "kungfu", file: "kungfu.swf", category: "retro" },
	{ name: "Prince of Persia", slug: "princeofpersia", file: "princeofpersia.swf", category: "retro" },
	{ name: "River City Ransom", slug: "rivercityransom", file: "rivercityransom.swf", category: "retro" },
	{ name: "Mortal Kombat 2", slug: "mortalkombat2", file: "mortalkombat2.swf", category: "retro" },
	{ name: "Frogger", slug: "frogger", file: "frogger.swf", category: "retro" },
	{ name: "Pacman", slug: "pacman", file: "pacman.swf", category: "retro" },
	{ name: "Zelda", slug: "zelda", file: "zelda.swf", category: "retro" },
	{ name: "Sonic", slug: "sonic", file: "sonic.swf", category: "retro" },

	// Special cabinets
	{ name: "Doom", slug: "doom", file: "doom.swf", category: "lightgun" },
	{ name: "Armor Trigger", slug: "armortrigger", file: "armortrigger.swf", category: "lightgun" },
	{ name: "Gunny Bunny", slug: "gunnybunny", file: "gunnybunny.swf", category: "lightgun" },
	{ name: "Flash Flash Revolution", slug: "flashflashrevolution", file: "flashflashrevolution.swf", category: "ddr" }
];
